# Generated by Django 2.2.7 on 2019-11-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfo',
            name='h_describ',
        ),
    ]
