# Generated by Django 2.2.7 on 2019-11-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=20, verbose_name='主机名')),
                ('h_ip', models.CharField(max_length=15, verbose_name='IP')),
                ('h_location', models.CharField(max_length=10, verbose_name='位置')),
                ('h_virorphy', models.CharField(max_length=10, verbose_name='类型')),
                ('h_mem', models.IntegerField(verbose_name='内存')),
                ('h_cpu', models.CharField(max_length=200, verbose_name='CPU型号')),
                ('h_cpus', models.IntegerField(verbose_name='CPU个数')),
                ('h_os', models.CharField(max_length=100, verbose_name='操作系统')),
                ('h_status', models.CharField(max_length=10,default="运行", verbose_name='状态')),
                ('h_describ', models.CharField(max_length=500, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('upwd', models.CharField(max_length=100, verbose_name='密码')),
                ('uphone', models.CharField(max_length=11, verbose_name='电话')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20, verbose_name='服务名称')),
                ('s_pid', models.IntegerField(verbose_name='PID')),
                ('s_status', models.CharField(choices=[('S', 'STOP'), ('R', 'RUNNING'), ('D', 'DEAD')], max_length=1, verbose_name='运行状态')),
                ('host_id', models.ForeignKey(on_delete=True, to='webuser.HostInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_add', models.BooleanField(default=False, verbose_name='增加')),
                ('p_del', models.BooleanField(default=False, verbose_name='删除')),
                ('p_chg', models.BooleanField(default=False, verbose_name='修改')),
                ('p_sel', models.BooleanField(default=False, verbose_name='查看')),
                ('user_id', models.ForeignKey(on_delete=True, to='webuser.User')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_totalmem', models.IntegerField(default=0, verbose_name='总内存')),
                ('m_freemem', models.IntegerField(default=0, verbose_name='空闲内存')),
                ('m_useage', models.IntegerField(default=0, verbose_name='使用率')),
                ('m_uptime', models.IntegerField(default=0, verbose_name='运行时间')),
                ('host_id', models.ForeignKey(on_delete=True, to='webuser.HostInfo')),
            ],
        ),
    ]
