# Generated by Django 2.2.7 on 2019-11-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='host_id',
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='host_id',
        ),
        migrations.DeleteModel(
            name='HostInfo',
        ),
        migrations.DeleteModel(
            name='Monitor',
        ),
        migrations.DeleteModel(
            name='Privilege',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
